package razen.microforge.core.mods;

import org.apache.log4j.BasicConfigurator;
import razen.microforge.core.io.FileOperations;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

public final class ModManagerTest {
    private ModManagerTest() {
    }

    public static void main(String[] args) throws Exception {
        BasicConfigurator.configure();
        var temp = Files.createTempDirectory("microforge-mod-manager-");
        try {
            var first = temp.resolve("First");
            var second = temp.resolve("Second");
            Files.createDirectories(first);
            Files.createDirectories(second);
            Files.writeString(first.resolve("mod_info.json"), descriptor("first", "First", "second"),
                    StandardCharsets.UTF_8);
            Files.writeString(second.resolve("mod_info.json"), stringVersionDescriptor("second", "Second", "first"),
                    StandardCharsets.UTF_8);
            Files.writeString(temp.resolve("enabled_mods.json"),
                    "\ufeff# generated by the launcher\n{\"enabledMods\":[\"first\",\"first\",\"missing\"]}\n",
                    StandardCharsets.UTF_8);

            var manager = new ModManager(temp);
            var firstMod = manager.getAvailableMod("first");
            var dependencies = firstMod.dependencies();
            require(dependencies.equals(java.util.List.of("second")),
                    "descriptor dependencies were not loaded: " + dependencies);
            require(firstMod.version() != null && "1.2.3".equals(firstMod.version().toString()),
                    "descriptor version was not loaded: " + firstMod.version());
            require(firstMod.dependencyVersions().get("second") != null
                            && "2.0".equals(firstMod.dependencyVersions().get("second").toString())
                            && firstMod.dependencyVersions().get("second").patch().isEmpty(),
                    "dependency version was not loaded: " + firstMod.dependencyVersions());
            var secondMod = manager.getAvailableMod("second");
            require(secondMod.version().major().equals("0.3") && secondMod.version().minor().equals("2")
                            && secondMod.version().patch().equals("1"),
                    "string descriptor version was not parsed with Starsector rules: " + secondMod.version());
            require(secondMod.dependencies().equals(java.util.List.of("first"))
                            && !secondMod.dependencyVersions().containsKey("first"),
                    "free-form dependency version affected dependency loading");
            require(manager.getEnabledMods().stream().map(ModSpec::id).toList().equals(
                            java.util.List.of("first")),
                    "enabled list did not preserve valid unique ids");
            require(manager.isEnabled("first") && !manager.isEnabled("missing"),
                    "enabled-id lookup did not match the loaded list");
            manager.disableMods(java.util.Set.of("first"));
            require(!manager.isEnabled("first"), "disabled mod remained enabled in memory");
            var enabledFile = Files.readString(temp.resolve("enabled_mods.json"), StandardCharsets.UTF_8);
            require(!enabledFile.contains("\"first\"") && enabledFile.contains("\"missing\""),
                    "disabling a mod did not preserve the rest of enabled_mods.json: " + enabledFile);
            System.out.println("ModManagerTest passed");
        } finally {
            FileOperations.deleteRecursively(temp);
        }
    }

    private static String descriptor(String id, String name, String dependency) {
        return "{\"id\":\"" + id + "\",\"name\":\"" + name
                + "\",\"version\":{\"major\":1,\"minor\":2,\"patch\":3}"
                + ",\"dependencies\":[{\"id\":\"" + dependency
                + "\",\"version\":{\"major\":2,\"minor\":0}}]}\n";
    }

    private static String stringVersionDescriptor(String id, String name, String dependency) {
        return "{\"id\":\"" + id + "\",\"name\":\"" + name
                + "\",\"version\":\"0.3.2.1\",\"dependencies\":[{\"id\":\""
                + dependency + "\",\"version\":\"custom\"}]}\n";
    }

    private static void require(boolean condition, String message) {
        if (!condition) {
            throw new AssertionError(message);
        }
    }
}
